### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by kikicat-meows** [kikicat-meows/opendumpster#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by samwalker191** [comment]
Looks good! Just a few notes. Please see below:

1. make sure all of your buttons change the cursor on hover. 
2. I should be able to click anywhere outside of the modal to close it
3. For the spacing stuff in the pictures below, try to get it to look more like OpenTable's spacing. And just make sure both forms have the same spacing.

![image](https://user-images.githubusercontent.com/49164119/72103806-d7085f00-32de-11ea-8c65-16b0b100e168.png)

_____________________________________________________________________________________________________________

![image](https://user-images.githubusercontent.com/49164119/72103814-dcfe4000-32de-11ea-87d7-6545c81d321a.png)

_____________________________________________________________________________________________________________

![image](https://user-images.githubusercontent.com/49164119/72103822-e25b8a80-32de-11ea-9ec4-5f7dc4a3684d.png)

_____________________________________________________________________________________________________________

![image](https://user-images.githubusercontent.com/49164119/72103950-22bb0880-32df-11ea-8a57-ca996285e5de.png)

**Comment by kikicat-meows** [comment]
* Fixed the above CSS styling - not gonna be exact but the spacing should be more even, added a bit more padding on the top (in the H2) to make it look nicer. 
* Focusing on input fields and buttons will now render correctly with no blue outlines.
* Clicking in modal container BUT NOT content will still close form properly.
* I purposely made the Open Dumpster thing lol, I was thinking to put more text in there to make it look nice.

**Comment by samwalker191** [comment]
Styling looks great now! 
The only thing left is the weird navigation when going from signin -> signup and then clicking out side of the form

**Comment by samwalker191** [comment]
Looks great!
Closing this issue.
